# Generated by Django 4.0.5 on 2022-06-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.EmailField(max_length=400),
        ),
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
